name: Sync
on:
  # Allow to run manually
  workflow_dispatch: {}
  # Additionally run once a week at 3am on Monday
  schedule:
    - cron:  '0 3 * * MON'

permissions:
  # To be able to access the repository with `actions/checkout` and to create a pull request
  contents: write
  pull-requests: write


jobs:
  sync:
    name: A to B
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Sync B
        run: |
          cp -a ./A/. B

      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "frederic_giloux@yahoo.com"
          git config --global user.name "fgiloux"
          git remote set-url origin https://fgiloux:${GITHUB_TOKEN}@github.com/fgiloux/ci-tests.git
          if [[ ! `git status --porcelain` ]]; then
            echo "No changes"
            exit 0
          fi
          git checkout -b pr/ci-wf/ci-sync
          git add ./B
          git commit -m "chore: Sync B"
          git push --set-upstream origin pr/ci-wf/ci-sync
          gh pr create -B "$${{ github.event.repository.default_branch }}" --title 'chore: Sync B' --body 'Created by GitHub action: Sync'


