name: Git push diff

on:
  push:

jobs:
  check-changes:
    name: Deduce changes
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.push.after }}
          persist-credentials: false

      - name: Check ${{ inputs.component }} code changes
        id: check-changes
        run: |
          git diff --unified=0 ${{ github.event.push.before }} --  test.yaml

